function [Hd,lpFilt] = LowPassFilt(varargin)
%HIGHPASSFILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 05-Jun-2017 16:40:41

% Elliptic Highpass filter designed using FDESIGN.HIGHPASS.

%% DEFAULTS
% All frequency values are in Hz.
FS = 30000;  % Sampling Frequency
FPASS = 150;     % Passband Frequency
FSTOP = 250;     % Stopband Frequency
APASS = 0.0001;  % Passband Ripple (dB)
ASTOP = 80;      % Stopband Attenuation (dB)
MATCH = 'both';  % Band to match exactly

%% PARSE INPUT PARAMETERS
for iV = 1:2:length(varargin)
    eval([upper(varargin{iV}) ' = varargin{iV+1};']);
end

%% DESIGN FILTER
% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.lowpass(FPASS, FSTOP, APASS, ASTOP, FS);
Hd = design(h, 'ellip', 'MatchExactly', MATCH);
lpFilt = designfilt('lowpassiir',  'StopbandFrequency', FSTOP, ...
                                   'PassbandFrequency', FPASS, ...
                                   'StopbandAttenuation', ASTOP, ...
                                   'PassbandRipple', APASS, ...
                                   'SampleRate', FS, ...
                                   'DesignMethod', 'ellip');


end