function [Hd,hpFilt] = HighPassFilt(varargin)
%HIGHPASSFILT Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 05-Jun-2017 16:40:41

% Elliptic Highpass filter designed using FDESIGN.HIGHPASS.

%% DEFAULTS
% All frequency values are in Hz.
FS = 30000;  % Sampling Frequency
FSTOP = 250;     % Stopband Frequency
FPASS = 350;     % Passband Frequency
ASTOP = 80;      % Stopband Attenuation (dB)
APASS = 0.0001;  % Passband Ripple (dB)
MATCH = 'both';  % Band to match exactly

%% PARSE INPUT PARAMETERS
for iV = 1:2:length(varargin)
    eval([upper(varargin{iV}) ' = varargin{iV+1};']);
end

%% DESIGN FILTER
% Construct an FDESIGN object and call its ELLIP method.
h  = fdesign.highpass(FSTOP, FPASS, ASTOP, APASS, FS);
Hd = design(h, 'ellip', 'MatchExactly', MATCH);
hpFilt = designfilt('highpassfir', 'StopbandFrequency', FSTOP, ...
                                   'PassbandFrequency', FPASS, ...
                                   'StopbandAttenuation', ASTOP, ...
                                   'PassbandRipple', APASS, ...
                                   'SampleRate', FS, ...
                                   'DesignMethod', 'kaiserwin');


end